---

dist: xenial

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-bibtex-extra biber

script:
  - make

deploy:
  provider: releases
  api_key: $GITHUB OAUTH TOKEN
  file:
    - project.pdf
  skip_cleanup: true
  overwrite: true
  draft: true
  # on:
  #   tags: true
